### ISSUE TITLE
Compile STM32F103C8 firmware from source

### ISSUE THREAD

**Issue by wmzart** [markniu/PandaPi#12]
Hello,

Where can I find the source of the firmware for the STFM32F103C8 controller?

I would like to try to build the source myself.

Thanks!

Marc

**Comment by wmzart** [comment]
User @keczejo already mentioned that the "... source code for stm is not public yet ...". [(See here)](https://github.com/markniu/PandaPi/issues/11#issuecomment-609736296). So when are these files going to be released?

**Comment by markniu** [comment]
After selling 1,000 of this board, the firmware will be open source, :)

**Comment by wmzart** [comment]
Cool! That would be fantastic.

**Comment by wmzart** [comment]
Either you have sold at least 1000 of these boards or you changed your mind. Nevertheless a big thanks for providing the source!

https://github.com/markniu/PandaPi/tree/master/firmware/pandapi_stm32f103
