### ISSUE TITLE
[info] Started to draw vector graphics for documentation.

### ISSUE THREAD

**Issue by Moorviper** [markniu/PandaPi#13]
![PandaPi](https://user-images.githubusercontent.com/3305254/81982827-a8a2e380-9632-11ea-8f4e-ea0442711639.png)
Hi mark for you to know i am currently do some vector graphics of your board which you can use for documentation.
It is not finished yet ... but in the work.

**Comment by markniu** [comment]
Great! Many others want this 3d file that I don't have.

**Comment by Moorviper** [comment]
![PandaPi](https://user-images.githubusercontent.com/3305254/82079034-718c0b00-96e2-11ea-96eb-82c1d2657851.png)
Unsure if i rotate all text in one direction. 
I don't draw the resistors but i have to check for the led's :D

**Comment by markniu** [comment]
that's great.Thank you so much!  
about the fans, I just draw this [image](https://github.com/markniu/PandaPi/wiki/How-to-wire),hope that help! 
![Uploading 图片.png…]()

I learn the Altium Designer tool, and had draw this[ board 3D file](https://drive.google.com/drive/folders/1Imnye9MxCWCUlUC2pw_A6A5WoUFMV1xj?usp=sharing) this week.
