### ISSUE TITLE
suggestion:  Differentiate 24v and non-24v fan sockets

### ISSUE THREAD

**Issue by ChrisWeiss** [markniu/PandaPi#15]
I really like the support for multiple fan voltages. It might be helpful to use different style sockets for the 24v fan sockets than the non-24v fan sockets, when things are that close together, it can be easy to plug things in incorrectly. With fans, the user may not find out until the fan burns out after a few hours at the wrong voltage. 

Maybe change socket style or color between the two types?

**Comment by Moorviper** [comment]
Only the 2nd row is adjustable.

**Comment by markniu** [comment]
That's a good suggestion, I will change the color of non -24v fan sockets.

**Comment by markniu** [comment]
![image](https://user-images.githubusercontent.com/13879340/89728738-1dcf5a80-da62-11ea-99b6-cd4baa2b4cbd.png)
