### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dgrammatiko** [markniu/PandaPi#18]
Does PandaPi supports (or will ever support) 2208 in UART mode?

**Comment by markniu** [comment]
Yes, the PandaPi supports TMC2208 now, and make sure this pin is uart,else you need to wire it.
![图片](https://user-images.githubusercontent.com/13879340/87932326-ec481c80-cabd-11ea-9ee9-c695ec57d986.png)

**Comment by dgrammatiko** [comment]
Nice, thanks
