### ISSUE TITLE
[feature request][hardware] add jumper for display

### ISSUE THREAD

**Issue by Moorviper** [markniu/PandaPi#20]
Hi.
It would be useful to add a jumper for that.
Display and ui looks great.
![Alt Text](https://static.wixstatic.com/media/0d0edf_0f88f150b0664634b3a59d1bcea59675~mv2.jpg/v1/fill/w_1840,h_749,al_c,q_85/0d0edf_0f88f150b0664634b3a59d1bcea59675~mv2.jpg)

**Comment by markniu** [comment]
agree! I will add it and send out to the factory this week

**Comment by Moorviper** [comment]
Done with rev 2.8
