### ISSUE TITLE
[feature-request] update octoprint to python 3

### ISSUE THREAD

**Issue by Moorviper** [markniu/PandaPi#25]
The last plugin which is shipped with the octopi image which was still only python 2 compatible is now updated.
It would be great if there would be a new base Image with the latest octoprint and python 3.

https://github.com/vitormhenrique/OctoPrint-Enclosure/commit/37796fafbee7b0c19cba7ea8a6a42d119539e0c5

greetings
Daniel

**Comment by markniu** [comment]
know a little of the python and octopi code. so I just download the latest octopi img. and replaced the kernel and put the Marlin into it.

**Comment by Moorviper** [comment]
closing due to https://github.com/markniu/PandaPi/issues/32
