### ISSUE TITLE
More information on runout sensor

### ISSUE THREAD

**Issue by dsancheznet** [markniu/PandaPi#28]
Please provide a more detailed information on the runout sensor, since I do not quite understand how to wire it up in version 2.5 of the board. I own this sensor:

https://es.aliexpress.com/item/32969817931.html?spm=a2g0s.9042311.0.0.3cfc63c0WZ4FaY

Which is apparently for an ender printer. Anyway, if I insert filament into the sensor, pins 1 and 3 get shorted. 
Where do I have to connect the pins... G + C or G + D or C + D or does it need to provide 3.3V or 5 V to the pins?

Best regards

**Comment by markniu** [comment]
connect it to pin G and C,  no need to provide 3.3V or 5V.

**Comment by dsancheznet** [comment]
Thank you!
